### ISSUE TITLE
[INITIATIVE] Create RESTful API

### ISSUE THREAD

**Issue by andreaswachs** [andreaswachs/gaas#20]
# Description

The project is envisioned to provide the Gaddag data structure as a Service to users. This means that they should be able consume our service through a RESTful API, allowing for simple integration into any other service that can make HTTP requests.

## Acceptance criteria

- [ ] Create Swagger definitions for the RESTful API
- [ ] Implemented the Swagger definition using the Plug framework for Elixir
- [ ] Tested the RESTful API using HTTPoison

## Breakdown

**TODO**

- [ ] put #id links here to tasks
