### ISSUE TITLE
[INITIATIVE] Word Search

### ISSUE THREAD

**Issue by andreaswachs** [andreaswachs/gaas#22]
# Description

The system should make full use of the Gaddag data structure, such that we can make something useful of out very spaceous data structure

## Acceptance criteria

- [ ] Implemented and tested a Word Search module
- [ ] Can find words from a collection of letters

## Breakdown
- [ ] put #id links here to tasks

**Comment by andreaswachs** [comment]
This is a duplicate
